"""empty message

Revision ID: c80696fdaf4c
Revises: 
Create Date: 2024-03-16 01:34:23.976959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c80696fdaf4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=500), nullable=True))
        batch_op.drop_column('phone_number')
        batch_op.drop_column('user_name')
        batch_op.drop_column('customer_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_password', mysql.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('user_name', mysql.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('phone_number', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('password')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
